# nixpacks.toml
[phases.setup]
cmds = [
    "apk add --no-cache ffmpeg",
    "apk add --no-cache python3 py3-pip",
    "pip3 install yt-dlp"
]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/server.js"